### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by OndrejSpanel** [allenai/sbt-plugins#285]
I have added `addSbtPlugin("org.allenai.plugins" % "allenai-sbt-plugins" % "1.5.2")` and `val myProject = project.in(file(".")).enablePlugins(NodeJsPlugin)` into my project.

I am unable to load the project, as it shows following error when loading into sbt:

```
java.lang.RuntimeException: Scala.js cannot be run in a forked JVM
        at scala.sys.package$.error(package.scala:27)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$52.app
ly(ScalaJSPluginInternal.scala:594)
        at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$52.app
ly(ScalaJSPluginInternal.scala:592)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47
)
        at sbt.EvaluateSettings$MixedNode.evaluate0(INode.scala:175)
        at sbt.EvaluateSettings$INode.evaluate(INode.scala:135)
        at sbt.EvaluateSettings$$anonfun$sbt$EvaluateSettings$$submitE
valuate$1.apply$mcV$sp(INode.scala:69)
        at sbt.EvaluateSettings.sbt$EvaluateSettings$$run0(INode.scala
:78)
        at sbt.EvaluateSettings$$anon$3.run(INode.scala:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown S
ource)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown
Source)
        at java.lang.Thread.run(Unknown Source)
```

**Comment by jkinkead** [comment]
It looks like you're using a plugin that's incompatible with some of our settings.

What if you try setting `fork.in(run) := false`?
